# Generated by Django 2.1.3 on 2018-11-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_auto_20181122_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='start_date',
        ),
    ]
