# Generated by Django 2.1.3 on 2018-11-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_auto_20181122_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='tickers',
        ),
        migrations.RemoveField(
            model_name='weightsimulation',
            name='simulation',
        ),
        migrations.RemoveField(
            model_name='weightsimulation',
            name='ticker',
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
        migrations.DeleteModel(
            name='WeightSimulation',
        ),
    ]
