language: python

services:
  - postgresql

before_install:
  - printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${NPM_TOKEN}\n" >> .npmrc

before_script:
  - psql -c "CREATE DATABASE datatrade;" -U postgres
  - psql -c "CREATE USER datatrade WITH PASSWORD 'datatrade';" -U postgres
  - psql -c "ALTER USER datatrade CREATEDB;" -U postgres
  - psql -c "ALTER ROLE datatrade SET client_encoding TO 'utf8';" -U postgres
  - psql -c "ALTER ROLE datatrade SET default_transaction_isolation TO 'read committed';" -U postgres
  - psql -c "ALTER ROLE datatrade SET timezone TO 'UTC';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE datatrade TO datatrade;" -U postgres

matrix:
  include:
    - language: python
      python:
        - 3.6
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test

    - language: node_js
      node_js:
        - 11.1
      install:
        - yarn install
      script:
        - yarn test
