language: python

services:
  - postgresql

before_install:
  - printf "@fortawesome:registry=https://npm.fontawesome.com/
    //npm.fontawesome.com/:_authToken=${NPM_TOKEN}\n" >> .npmrc

before_script:
  - psql -c "CREATE DATABASE datatrade;" -U postgres
  - psql -c 'create database test_db;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres

matrix:
  include:
    - language: python
      python:
        - 3.6
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test

    - language: node_js
      node_js:
        - 11.1
      install:
        - yarn install
      script:
        - yarn test
