language: python

before_script:
  - psql -c "CREATE DATABASE datatrade;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres

matrix:
  include:
    - language: python
      python:
        - 3.6
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test

    - language: node_js
      node_js:
        - 11.1
      install:
        - yarn install
      script:
        - yarn test
