# Generated by Django 2.1.1 on 2018-10-16 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('time_zone', models.IntegerField(choices=[(-11, '(-11) Midway'), (-10, '(-10) Midway'), (-9, '(-9) Honolulu'), (-8, '(-8) Adak'), (-7, '(-7) Anchorage'), (-6, '(-6) San Francisco'), (-5, '(-5) San Salvador'), (-4, '(-4) St. Louis'), (-3, '(-3) Philadelphia'), (-2, '(-2) Rio de Janero'), (-1, '(-1) Nuuk'), (0, '(0) Praia'), (1, '(1) London'), (2, '(2) Paris, Berlin'), (3, '(3) Minsk, Djibouti'), (4, '(4) Baku, Teheran'), (5, '(5) Karachi'), (6, '(6) Omsk'), (7, '(7) Jakarta'), (8, '(8) Nanjing'), (9, '(9) Tokyo'), (10, '(10) Brisbane'), (11, '(11) Sidney'), (12, '(12) Wake island')], default=0, validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(12)])),
                ('opening_time', models.DateTimeField(verbose_name='local opening time')),
                ('closing_time', models.DateTimeField(verbose_name='local closing time')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('home_url', models.CharField(max_length=200)),
                ('api_url', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True, null=True)),
                ('exchanges', models.ManyToManyField(to='exchange.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.Exchange')),
            ],
        ),
    ]
