# Generated by Django 2.1.1 on 2018-10-19 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20181019_1503'),
        ('exchange', '0005_auto_20181019_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.Provider')),
            ],
        ),
        migrations.AlterField(
            model_name='exchange',
            name='time_zone',
            field=models.IntegerField(choices=[(-11, '(-11) Midway, Pago Pago'), (-10, '(-10) Honolulu'), (-9, '(-9) Anchorage'), (-8, '(-8) Los Angeles'), (-7, '(-7) Denver'), (-6, '(-6) Chicago'), (-5, '(-5) New York'), (-4, '(-4) Santiago'), (-3, '(-3) Rio de Janero'), (-2, '(-2) Fernando de Noronha'), (-1, '(-1) Praia'), (0, '(0) UTC London'), (1, '(1) Paris, Berlin'), (2, '(2) Athen'), (3, '(3) Djeddah'), (4, '(4) Dubai'), (5, '(5) Karachi'), (6, '(6) Dhaka'), (7, '(7) Bangkok, Jakarta'), (8, '(8) Hong-Kong, Nanjing'), (9, '(9) Tokyo'), (10, '(10) Sidney'), (11, '(11) Noumea'), (12, '(12) Welligton')], default=0, validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterUniqueTogether(
            name='tick',
            unique_together={('company', 'provider', 'date')},
        ),
    ]
