# Generated by Django 2.1.1 on 2018-10-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20181019_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tick',
            name='close',
            field=models.IntegerField(),
        ),
    ]
