# Generated by Django 2.1.1 on 2018-10-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20181019_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tick',
            name='close',
            field=models.FloatField(),
        ),
    ]
