# Generated by Django 2.1.1 on 2018-10-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20181022_1505'),
        ('exchange', '0008_auto_20181019_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickAdjusted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_adj', models.FloatField()),
                ('high_adj', models.FloatField()),
                ('low_adj', models.FloatField()),
                ('close_adj', models.FloatField()),
                ('volume_adj', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.Provider')),
            ],
            options={
                'ordering': ['company', 'date', 'provider'],
            },
        ),
        migrations.AlterModelOptions(
            name='tick',
            options={'ordering': ['company', 'date', 'provider']},
        ),
        migrations.AlterModelOptions(
            name='ticker',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterUniqueTogether(
            name='tickadjusted',
            unique_together={('company', 'provider', 'date')},
        ),
    ]
