# Generated by Django 2.1.1 on 2018-10-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_auto_20181022_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='close_adj',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='dividend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='high_adj',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='low_adj',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='open_adj',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='split',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='volume_adj',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
