# Generated by Django 2.1.1 on 2018-10-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20181019_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualEPS', models.FloatField(default=0.0)),
                ('consensusEPS', models.FloatField(default=0.0)),
                ('estimatedEPS', models.FloatField(default=0.0)),
                ('announceTime', models.IntegerField(choices=[(0, 'N/A'), (1, 'Before open'), (2, 'During trading'), (3, 'After close')], default=0)),
                ('numberOfEstimates', models.IntegerField(default=0)),
                ('EPSSurpriseDollar', models.FloatField(default=0.0)),
                ('EPSReportDate', models.DateField(blank=True, null=True)),
                ('fiscalEndDate', models.DateField(blank=True, null=True)),
                ('yearAgo', models.FloatField(default=0.0)),
                ('yearAgoChangePercent', models.FloatField(default=0.0)),
                ('estimatedChangePercent', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dividend',
            name='fiscalPeriod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.FiscalPeriod'),
        ),
    ]
