# Generated by Django 2.1.1 on 2018-10-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20181019_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dividend',
            new_name='Earning',
        ),
    ]
