# Generated by Django 2.1.1 on 2018-10-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20181019_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='yearAgoChangePercent',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
