# Generated by Django 2.1.1 on 2018-10-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20181019_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='EPSSurpriseDollar',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
