# Generated by Django 2.1.1 on 2018-10-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20181019_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='actualEPS',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='earning',
            name='consensusEPS',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='earning',
            name='estimatedChangePercent',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='earning',
            name='estimatedEPS',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='earning',
            name='numberOfEstimates',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='earning',
            name='yearAgo',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
