# Generated by Django 2.1.1 on 2018-10-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20181019_1302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='earning',
            unique_together={('company', 'fiscalPeriod')},
        ),
    ]
